# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Push GCR and Build Deploy to GKE

on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: devsecops-cluster-1    # Add your cluster name here.
  GKE_ZONE: asia-southeast1-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: mydevsecopsblog # Add your deployment name here.
  IMAGE: hugosite

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: docker-build-push-gcr-update-gke-deployment-action
  # You may pin to the exact commit or the version.
  # uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@a3c865ea7eeddc9aa68921cf6e7bff13d6cb5d6a
      uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@1.4
      with:
    # Base64 encoded service account JSON from GCP IAM service account
          service_account: ${{ secrets.GKE_SA_KEY }}
          # Cluster Zone
          zone: asia-southeast1-a 
          # Project ID from GCP
          project_id: devsecopstesting
          # GCR registry host, It could be gcr.io/us.gcr.io/eu.gcr.io/asia.gcr.io
          registry: gcr.io
          # Name of the image
          image_name: hugosite
          # Name of GKE cluster
          cluster: devsecops-cluster-1
          # Namespace of the deployment
          namespace: default
          # Name of the deployment which needs to be update
          deployment: hugosite
          # Name of container whose image needs to be updated
          container: hugosite-sha256-1
    
